### ISSUE TITLE
Wrongly aligned server folders

### ISSUE THREAD

**Issue by shrimpyPL** [DiscordStyles/HorizontalServerList#10]
as in topic, server folders are not aligned at all
![obraz](https://user-images.githubusercontent.com/89362433/130373681-d485c379-7772-496f-9f9c-4548832de045.png)
![obraz](https://user-images.githubusercontent.com/89362433/130373704-da83f5d5-0274-44d6-a9d0-7fe3f3c23035.png)

**Comment by Gibbu** [comment]
This is the result of your other theme. Nothing to do with Horizontal Server List.

![image](https://user-images.githubusercontent.com/20338746/130532500-3874ef5e-23f8-44bc-81ac-c89dfe366d49.png)
