### ISSUE TITLE
Feature request: place "pills" bellow server icons

### ISSUE THREAD

**Issue by xan2622** [DiscordStyles/HorizontalServerList#14]
🟢 **Feature Request:**
Would it be possible to place "pills" bellow server icons?

🟢 **Mock-up:**

![01 212547](https://user-images.githubusercontent.com/1732773/139739175-304c8262-ff2a-4ffd-8f83-a1d38d384131.jpg)

🟢 **Infomation:**  
- Here are CSS properties that might need to be modified: 
- ` pill-1z4sAY wrapper-sa6paO `
- ` #app-mount .guilds-1SWlCJ [class*="pill"] `

🟢 **Additional context:**  
- OS: *((Windows 10 Pro 64 bits))*  
- Web Browser: Firefox 93.0
- HorizontalServerList version: cee42ef

**Comment by Gibbu** [comment]
You can ask around in the BD servers on how to achieve this. But I'm not going to add this.
