### ISSUE TITLE
Folder width is not appropriate to the contents of the folder

### ISSUE THREAD

**Issue by Slddev** [DiscordStyles/HorizontalServerList#15]
**Describe the bug**  
Folder width is too small/big.

**To Reproduce**  

1. Install the theme
2. Add many folders with servers in them.
3. Expand them
4. You should see that in the folder background in the very right is a lot bigger than the one on the very left.

**Screenshots**  
On the very left:
![image](https://user-images.githubusercontent.com/74999267/141320673-d06d99ab-5180-40ce-94fc-146e6666be77.png)

On the very right:
![image](https://user-images.githubusercontent.com/74999267/141320793-11484a7f-19ec-452b-85df-a17889f8c85a.png)

**Infomation (please complete the following information):**  
Discord channel: *Canary*  
OS: *Windows*  
Mod: *BetterDiscord*  
Discord language: *English*

**Comment by Gibbu** [comment]
Should be fixed now?

**Comment by Slddev** [comment]
Yep.
