### ISSUE TITLE
Brief description of the bug

### ISSUE THREAD

**Issue by wife** [DiscordStyles/HorizontalServerList#16]
**Describe the bug**  
*Does not work on latest version of Discord Canary*  

**To Reproduce**  
*open discord, vertical 😔*  

**Screenshots**  
*((If applicable, add screenshots to help explain your problem))*  
[https://thecheating.party/i/ya5j1d.png](Issue)

**Infomation (please complete the following information):**  
Discord channel: *((Stable/PTB/Canary))*  Canary
OS: *((Windows/Linux/OSX))*  Win10 20h2
Mod: *((BetterDiscord/Powercord))*  Powercord
Discord language: *((Your language))*  English

**Comment by Gibbu** [comment]
Correct the newest Cancary version has changed a lot of things. And won't be fixed until it comes to Stable.
Discord has a history of updating, reverting, updating, changing in span of a couple of hours to days.

It's pretty much a waste of time to actively support Canary.
