### ISSUE TITLE
HorizontalServerList with Float theme

### ISSUE THREAD

**Issue by yogeshvar** [DiscordStyles/HorizontalServerList#24]
Thanks [MaenDisease](https://github.com/maenDisease) for the [Float Theme](https://github.com/maenDisease/Float)

It would be so cool if HorizontalServerList could do something like this.

P.S: I have achieved this but modifying the HTML in dev tools.

https://user-images.githubusercontent.com/17572818/156601218-9dd7ac8d-dcf9-48ab-afad-1afe7f5fd35c.mov

.

But currently, the avatar floats over the upload button
<img width="377" alt="Screen Shot 2022-03-04 at 2 25 50 AM" src="https://user-images.githubusercontent.com/17572818/156601633-b9a8fe4f-8e8c-4ec9-8d18-d442168f1b90.png">

Is there any possible way we could do this with just the theme?

**Comment by Gibbu** [comment]
What as this got to do with Horizontal Server List?

**Comment by yogeshvar** [comment]
Apologies for that, my bad.
