### ISSUE TITLE
Server tooltipPointer top not important

### ISSUE THREAD

**Issue by kyleshrader** [DiscordStyles/HorizontalServerList#25]
**Describe the bug**  
Using betterdiscord with the horizontalserverlist plugin provided with clearvision, the tooltippointer's top property is not respected, causing the pointer to be displaced covering a small portion of the tooltip text.

**To Reproduce**
Use the attached BetterDiscord theme:
[clear-vision-lightgrey-custom.theme.zip](https://github.com/DiscordStyles/HorizontalServerList/files/8633841/clear-vision-lightgrey-custom.theme.zip)
(*github doesn't support .theme, zipping*)

**Screenshots**  
The pointer can be seen overlapping the tooltip text:
![image](https://user-images.githubusercontent.com/5632571/166999684-dcd92632-c178-4185-8206-e2cfe2e0d72d.png)

Custom CSS resolving the issue, moving the pointer to the top of the tooltip:
![image](https://user-images.githubusercontent.com/5632571/167000070-6a33033f-5563-41ac-856a-42bdafed080f.png)

**Infomation:**  
Discord channel: Stable
OS: Windows
Mod: BetterDiscord, ClearVision 6.3.0, HorizontalServerList, RadialStatus
Discord language: English

**Additional context**  
A workaround is to use the following in BetterDiscord's custom css:
```css
[class*=tooltipRight] > [class*=tooltipPointer] {
    top: -5px !important;
}
```

**Comment by Gibbu** [comment]
Fixed.
