### ISSUE TITLE
Small black triangle smudge appear on every server's name, verified mark.

### ISSUE THREAD

**Issue by xMarvelous** [DiscordStyles/HorizontalServerList#26]
**Describe the bug**  
Server's name text bug with small black smudge at the first letter or sometime on verified mark on some server.

**To Reproduce**  
It just appear like that no need to reproduce.

**Screenshots**  
The bug on text: https://i.imgur.com/Z1zqIPM.png  
On server verified mark: https://i.imgur.com/4qBOF3W.png

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows 11 latest version
Mod: BetterDiscord 1.5.3  
Discord language: English

**Comment by Gibbu** [comment]
Fixed.
