### ISSUE TITLE
Brief description of the bug

### ISSUE THREAD

**Issue by eesraa88** [DiscordStyles/HorizontalServerList#27]
**Describe the bug**  
*((A clear and concise description of what the bug is))*  
Since yesterday, the padding on the very top of discord has been removed causing the server icons to be overlapped by the discord logo on the top left
**To Reproduce**  
*((Steps to reproduce the behavior))*  
Enable the plugin and move the server list
**Screenshots**  
*((If applicable, add screenshots to help explain your problem))*  
https://steady.is-fi.re/AEzEA6E.png
**Infomation (please complete the following information):**  
Discord channel: *((Stable))*  
OS: *((Windows))*  
Mod: *((BetterDiscord))* 
Discord language: *((English))*

**Comment by Gibbu** [comment]
Should be fixed?

**Comment by eesraa88** [comment]
fixed 👍
