### ISSUE TITLE
I can't scroll sideways across my joined servers on Windows 10

### ISSUE THREAD

**Issue by desbest** [DiscordStyles/HorizontalServerList#29]
### Describe the bug
I can't scroll sideways across my joined servers on Windows 10
I use my laptop's trackpad

### To Reproduce  
Scroll sideways across your joined server listing

**Expected behaviour:** The listing should scroll across as desired

**Actual behaviour:** no scrolling happens

### Screenshots
N/A

### Infomation (please complete the following information)
**Discord channel**: Stable
**OS**: Windows 10 21H2
**Mod**: Goosemod
**Discord language**: English (UK)

### Additional context
It works in Firefox 103

**Comment by Gibbu** [comment]
Scroll up and down, not left and right. There's no way for CSS to change the scroll direction.

**Comment by desbest** [comment]
No I mean that when using my laptop, if I use my trackpad to swipe left and right by holding down two fingers at the same time, the server listing should move across for me to see the rest of my servers.

This happens in the web browser but not the desktop client.


Whether the action of the server listing moving along on the horizontal pane, is technically scrolling up and down rather than left to right, that is irrelevant.

**Comment by Gibbu** [comment]
Doesn't seem to be a problem for me.

https://user-images.githubusercontent.com/20338746/184533897-280d3644-69cd-43b0-a56f-26478c2e14d2.mov

**Comment by Gibbu** [comment]
Oops. Now that I reread your issue, I also get this. And like I said before. There's no way for me to fix this. Firefox seems to be smart enough to figure out the trick used and apply the necessary gestures.
