### ISSUE TITLE
Explore Servers

### ISSUE THREAD

**Issue by loonaluxx** [DiscordStyles/HorizontalServerList#32]
The explore server button covers the button to open my DM list so i can only open a dm through a server or through notification.

![image](https://user-images.githubusercontent.com/119894267/205734619-a4adcc26-cddf-40f8-9919-584be949339c.png)

On  Stable
On Windows
BetterDiscord
English

**Comment by Gibbu** [comment]
Do you have any CustomCSS enabled? Because it works just fine for me on MacOS and Windows.

**Comment by loonaluxx** [comment]
i had a font changer at the time but i removed it and it is still doing this

**Comment by loonaluxx** [comment]
i changed to ptb its fine now
