### ISSUE TITLE
Server icon size not being applied

### ISSUE THREAD

**Issue by HollyCeuin** [DiscordStyles/HorizontalServerList#36]
### Describe the bug
The icon size no longer applies to the icons and just the space the icons sit in.

### To Reproduce  
Change the icons size

### Screenshots
![image](https://user-images.githubusercontent.com/96226750/222263296-86f07e1a-c0fa-47cd-88f2-ede92dd6db9e.png)

### Infomation (please complete the following information)
Discord channel: *Stable
OS: Windows
Mod: BetterDiscord
Discord language: English

**Comment by LamaanVFX** [comment]
same issue ever since 1.8.5 update
