### ISSUE TITLE
Horizontal Server List not working

### ISSUE THREAD

**Issue by Breetlez** [DiscordStyles/HorizontalServerList#41]
Horizontal Server List stopped working after Ptb 237772 (21b7a7d) update 

**Discord channel**: *Canary*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*

**Comment by Brycero** [comment]
Looks like a class change. I was able to get it working again by replacing ``.app-3xd6d0`` with ``.app-2CXKsg``
```css
#app-mount .app-2CXKsg .base-2jDfDU {
```

**Comment by Gibbu** [comment]
I don't really care about Canary updates. Use Stable.
