### ISSUE TITLE
Discord Server is expired or I cannot join 

### ISSUE THREAD

**Issue by LawMixer** [DiscordStyles/HorizontalServerList#43]
### Describe the bug
expired link in the themes information

### To Reproduce  
go to your themes -> discord server

### Infomation (please complete the following information)
https://i.imgur.com/3THb3fP.png

**Comment by LawMixer** [comment]
https://i.imgur.com/qBQPEds.png

**Comment by Gibbu** [comment]
It's not expired just locked.
