### ISSUE TITLE
no spacing between servers unless in a folder

### ISSUE THREAD

**Issue by Elmo442** [DiscordStyles/HorizontalServerList#48]
no spacing between servers unless in a folder after discord updated to:
stable 268194 (9266b7f) Host 1.0.9034 x86 (44142) Windows 10 64-bit (10.0.19045)
with English discord, Polish Windows, and VENCORD 7b96071(Standalone)

I don't know I just updated discord, tried to disable plugins but it doesn't change a thing

Squished servers
![image](https://github.com/DiscordStyles/HorizontalServerList/assets/85043048/e0e58579-d07b-41c5-9b4c-73e91180109c)

is fine when theme disabled
![image](https://github.com/DiscordStyles/HorizontalServerList/assets/85043048/22e71b5c-1e65-4512-b600-79361019bc0c)

**Comment by TuxTheAstronaut** [comment]
same issue here after closing and reopening discord the theme now has no spacing

**Comment by o5k** [comment]
Also causes DMs to have too much spacing instead

**Comment by robwhitewick** [comment]
most recent commit causes servers to have 10px extra of spacing.

**Comment by o5k** [comment]
looks like it's fixed now by #49 :tada: thank you for your work!

**Comment by Elmo442** [comment]
The issue was indeed resolved in patch #49  TYSM Luk1337
remember to also check your themes settings, to make sure you have your spacing set properly

I will try to mark the issue as resolved
