### ISSUE TITLE
Seems broken?

### ISSUE THREAD

**Issue by qwuzzy** [DiscordStyles/HorizontalServerList#5]
When I activate this plugin it remove my settings button and text box. I can't scroll through the chat either. It also doesn't seem to like loading stuff not in the cache.
![Discord_OnprSrO4R6](https://user-images.githubusercontent.com/32120669/113645328-81367a00-963b-11eb-829b-92eef8980bad.png)

**Comment by ItsMartin030** [comment]
Same problem over here.

**Comment by Gibbu** [comment]
The settings button should be fixed.
Things not loading isn't a cause of Horizontal Server List.

**Comment by ItsMartin030** [comment]
Okay, but when I disable the plugin everything works. Strange...

**Comment by ItsMartin030** [comment]
Alright it works now like before, thank you very much Gibbu!

**Comment by qwuzzy** [comment]
> The settings button should be fixed.
> Things not loading isn't a cause of Horizontal Server List.

Thank you for the quick fix, everything seems to be working now :)
