### ISSUE TITLE
Latest Discord update makes the bar not show up.

### ISSUE THREAD

**Issue by Benji7010** [DiscordStyles/HorizontalServerList#51]
### Describe the bug
The server bar doesn't show up when using the plugin anymore.

### To Reproduce  
Use plugin after updating Discord

### Screenshots
![image](https://github.com/DiscordStyles/HorizontalServerList/assets/82925364/e64de9cf-7ed5-4dd0-b85d-a7bb624cc69e)

### Infomation (please complete the following information)
**Discord channel**: Stable
**OS**: Windows
**Mod**: Vencord Dev
**Discord language**: English

### Additional context
Latest Discord update said to break many themes. From the looks of it, this includes this theme.

**Comment by SPACED0UBT** [comment]
Same issue here. Resetting Vesktop had no change

**Comment by TheMelancholyOfGigi198** [comment]
Same issue

**Comment by AveAcVale** [comment]
Plus

**Comment by captainredbleach** [comment]
Same

**Comment by Gibbu** [comment]
I am aware of the issue. Please do not comment on the post with "same", it does not help in any way.

**Comment by Gibbu** [comment]
Fixed. Re-enable your theme.
