### ISSUE TITLE
Theme Broke With Discord Update

### ISSUE THREAD

**Issue by OnlyRedx** [DiscordStyles/HorizontalServerList#52]
### Describe the bug
I believe the theme broke with the Discord update

### To Reproduce  
Try to use them with BetterDiscord on the newest Discord update.

### Screenshots
n/a

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English (EN)*  

### Additional context
Just wondering if it autoupdates on BetterDiscord or would we have to redownload the theme. If we have to redownload is there a way to get notifications for updates?

**Comment by Gibbu** [comment]
Fixed
