### ISSUE TITLE
HSL-server-alignment no longer works

### ISSUE THREAD

**Issue by ddeityy** [DiscordStyles/HorizontalServerList#58]
### Describe the bug
--HSL-server-alignment seems to be stuck on default flex-start, changing it to center / flex-end doesn't work

### To Reproduce  
* Set --HSL-server-alignment to center or flex-end

### Screenshots
![image](https://github.com/user-attachments/assets/c796e2c8-51b5-4cf6-952e-3985c1030bf3)
![image](https://github.com/user-attachments/assets/72fec838-c50e-4152-9ef6-0eb8c794c79a)

### Infomation (please complete the following information)
**Discord channel**: *Stable*
**OS**: *Linux Fedora 40 KDE Wayland*
**Mod**: *Vesktop, BetterDiscord*
**Discord language**: *English*

* Vesktop Version
```
stable 348981 (ff756ae) Build Override: N/A
Vencord fcece61 (Vesktop v1.5.3)
Electron 31.1.0
Chromium 126.0.6478.114
```

* BetterDiscord Flatpak Version
```
BetterDiscord Core v1.10.2
stable 348981 (ff756ae)
Host 0.0.74 x64
Build Override: N/A Linux 64-bit (6.11.10-200.fc40.x86_64)
```

**Comment by Gibbu** [comment]
Fixed
