### ISSUE TITLE
The spacing between the servers displayed in the open folder has disappeared.

### ISSUE THREAD

**Issue by Czerwony150** [DiscordStyles/HorizontalServerList#59]
### Screenshots
In folder:
![image](https://github.com/user-attachments/assets/cc2f7b7a-6f9b-4fa9-b163-4074918b7dc1)
Normal:
![image](https://github.com/user-attachments/assets/d922c46b-555e-4f6b-a156-163cd131efec)

### Infomation
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *Polish*

**Comment by Gibbu** [comment]
Fixed
