### ISSUE TITLE
Server list does not disappear when watching Go Live stream in fullscreen mode

### ISSUE THREAD

**Issue by PandaDriver156** [DiscordStyles/HorizontalServerList#6]
Entering fullscreen mode on a go live stream will make servers disappear from the list, however the list itself will stay on the top, which results in the stream being smaller.

Here is an example:
![Image](https://user-images.githubusercontent.com/46034537/116360136-e4ad6500-a7ff-11eb-90b7-6f6766b59157.png)

**Comment by Void48** [comment]
Damn 16 days ago. I messaged him on Discord

**Comment by sarahkittyy** [comment]
I have this issue too :)

**Comment by Gibbu** [comment]
Fixed.
