### ISSUE TITLE
Latest Discord Update Breaks Server List

### ISSUE THREAD

**Issue by Mythra** [DiscordStyles/HorizontalServerList#61]
### Describe the bug

I just barely hit "Update" on Discord PTB, and now horizontal server list seems to be broken.
Big change seems to be in class names.

The new class names seem to be: `guilds_c48ade` as opposed to any of the other classes currently listed in the CSS.

### To Reproduce  

Update to latest PTB, and notice the list isn't horizontal.

### Screenshots

![Discord Light Mode in RGD with a vertical guilds list.](https://github.com/user-attachments/assets/74c3b66c-648d-4ef6-ba03-500cb52b7611)

### Infomation (please complete the following information)
**Discord channel**: PTB
**OS**: Windows
**Mod**: BetterDiscord
**Discord language**: English

**Comment by Gibbu** [comment]
I don't support support PTB/Canary as they change far too frequently. Use stable or wait for the update to be pushed to stable.

**Comment by Mythra** [comment]
FWIW I am aware, i just figured I'd open to let you know breaks were coming (figured since the form asked there might be some of that), sorry to spam the issue tracker.
