### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by KK-Designs** [DiscordStyles/HorizontalServerList#8]
The base.css import code returns 404. Looks like the GitHub pages were taken down.

**Comment by Gibbu** [comment]
All my themes got a structure change meaning the `base.css` file doesn't exist anymore.

All you have to do is just change the end of the url from `base.css` to `dist/HorizontalServerList.css`.
Example with Frosted Glass:
![image](https://user-images.githubusercontent.com/20338746/127092446-488b393d-1eb1-43f1-b75c-3d07aad2044f.png)

**Comment by KK-Designs** [comment]
It works now thanks!
